# Generated by Django 3.1.3 on 2020-11-28 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee'),
        ),
    ]
