# Generated by Django 3.1.3 on 2020-12-01 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201127_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dimensions', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('Vehicule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='id',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='Warehouse_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(default='Worker', max_length=100),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee'),
        ),
        migrations.CreateModel(
            name='Works_At',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Warehouse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
                ('Worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
            options={
                'unique_together': {('Worker_id', 'Warehouse_id')},
            },
        ),
    ]
