# Generated by Django 3.1.3 on 2020-12-01 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201201_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicule',
            new_name='Vehicle',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='Vehicule_id',
            new_name='Vehicle_id',
        ),
    ]
