# Generated by Django 3.1.3 on 2020-12-01 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201201_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('Route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Path', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Transaction_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('Route_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.route')),
                ('WH_Receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='WH_Sender_id', to='api.warehouse')),
                ('WH_Sender_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='WH_Receiver_id', to='api.warehouse')),
            ],
        ),
    ]
