# Generated by Django 3.1.3 on 2020-12-02 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201201_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Cid', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('Caddress', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='Item_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Transaction_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='Vehicle_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('Transaction_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.transaction')),
                ('Item_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.item')),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Unnamed', max_length=100)),
                ('Total_space', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('Warehouse_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
            ],
            options={
                'unique_together': {('Warehouse_id', 'Name')},
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('Transaction_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.transaction')),
                ('Admin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('Transaction_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.transaction')),
                ('Exec_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Item_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('Subsection_name', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.subsection')),
                ('Warehouse_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.warehouse')),
            ],
            options={
                'unique_together': {('Warehouse_id', 'Subsection_name', 'Item_id')},
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(default=1)),
                ('Status', models.BooleanField(default=False)),
                ('Cid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('Driver_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
                ('Item_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.item')),
                ('Route_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.route')),
            ],
            options={
                'unique_together': {('Cid', 'Item_id')},
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('Vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
            options={
                'unique_together': {('Vehicle_id', 'Driver_id')},
            },
        ),
    ]
